export const SHARED_PACKAGE_NAME = '@ai-agentic-english/shared';

export * from './errors';
export * from './auth/extractUserId';
export * from './dto/user';
export * from './dto/learning-materials';
export * from './dto/memory-progress';
export * from './dto/offline';
export * from './env';
export * from './events/achievementUnlocked';
export * from './events/createEvent';
export * from './events/base';
export * from './events/eventBus';
export * from './events/kafkaConsumer';
export * from './events/kafkaEventBus';
export * from './events/learningPathReady';
export * from './events/reviewDue';
export * from './events/userUpserted';
export * from './http/asyncHandler';
export * from './http/internal';
export * from './http/internalHttpClient';
export * from './notifications/novuClient';
export * from './testing';
